version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: michael-krakovsky
        BUILD_FOLDER: Personal_Website
        BUILD_ENV: "test"
phases:
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
    post_build:
         commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes